name: Build and Release Zip

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Zip Bundle
        run: |
          mkdir build
          # Copy all files to a directory named after the plugin
          rsync -av --progress . build/smtp-for-sendbyte --exclude build --exclude .git --exclude .github --exclude README.md --exclude assets/screenshot-\*.png --exclude assets/icon-\*.png --exclude assets/banner-\*.png
          cd build
          zip -r smtp-for-sendbyte.zip smtp-for-sendbyte

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smtp-for-sendbyte-plugin
          path: build/smtp-for-sendbyte.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: build/smtp-for-sendbyte.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
